<a href="https://colab.research.google.com/github/ArtDaryl/IntroToNumericalMethods/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and its Operations

In [3]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
b[0]=7

[[1 2 3]
 [4 5 6]]
(2, 3)


In [5]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
d = np.full((2,2),4)
print(d)

[[4 4]
 [4 4]]


In [8]:
e = np.eye(2)
print(e)

[[1. 0.]
 [0. 1.]]


In [9]:
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]])
print(e)

[1 5 9]


In [10]:
f = np.empty((0,10))
print(f)

[]


In [13]:
g = np.zeros((2,2))
print(g)

[[0. 0.]
 [0. 0.]]


In [16]:
e = np.eye(2)
g = np.zeros((2,2))
print(e+g)
print(e-g)
print(g-e)


[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[-1.  0.]
 [ 0. -1.]]
