<a href="https://colab.research.google.com/github/ArtDaryl/IntroToNumericalMethods/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations


#Python Exercise 2
Test Content : Create a NumPy program that performs the operations of the given matrices:

1.sum = A +B

2.difference1 = B - A

3.difference2 = A - B

In [4]:
import numpy as np
a = np.array([[-5,0],[4,1]])
b = np.array([[6,-3],[2,3]])

In [6]:
print(a+b) #sum of A+B

[[ 1 -3]
 [ 6  4]]


In [7]:
print(b-a) #difference of b-a

[[11 -3]
 [-2  2]]


In [8]:
print(a-b) #difference of a-b

[[-11   3]
 [  2  -2]]
